spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db?serverTimezone=GMT%2B8
    username: root
    password: 961126
#spring:
#  datasource:
#    url: jdbc:mysql://121.36.10.175:3306/gas_aws?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
#    username: root
#    password: D@^CtH%7Tjwa
#    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8888